version: '3.4'

services:
  broker:
    image: broker
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: broker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: