# Generated by Django 5.0.7 on 2024-07-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0001_initial"),
    ]

    def add_banks(apps, schema_editor):
        Bank = apps.get_model("commons", "Bank")

        banks_data = [
            "Banco Do Brasil S.A (BB)",
            "Bradesco S.A.",
            "Banco Digio S.A.",
            "Nu Pagamentos S.A (Nubank)",
        ]

        for bank in banks_data:
            Bank.objects.create(name=bank)

    operations = [
        migrations.RunPython(add_banks),
    ]
